// pages/[city].js
import React, { useEffect, useState } from "react";
import Header from "../components/Header/Header";
import Main from "../components/Main/Main";
import ProvidersInCity from "../components/ProvidersInCity/ProvidersInCity";
import AboutUs from "../components/AboutUs/AboutUs";
import SliderTariffsMain from "../components/SliderTariffsMain/SliderTariffsMain";
import Advantages from "../components/Advantages/Advantages";
import ConnectionSteps from "../components/ConnectionSteps/ConnectionSteps";
import HelpForm from "../components/HelpForm/HelpForm";
import Questions from "../components/Questions/Questions";
import Cities from "../components/Cities/Cities";
import Newsletter from "../components/NewsLetter/NewsLetter";
import Footer from "../components/Footer/Footer";
import PopUpLead from "@/components/PopUpLead/PopUpLead";
import PopUpAgreement from "@/components/PopUpAgreement/PopUpAgreement";
import PopUpPolicy from "@/components/PopUpPolicy/PopUpPolicy";
import Head from "next/head";
import api from "../../public/host/host.js";

const CityPage = ({ cityData }: { cityData: any }): JSX.Element => {
  if (!cityData) return <div>Loading...</div>;
  console.log(cityData);
  return (
    <>
      <Head>
        <title>
          Тарифы на интернет в {cityData.infoDistrict.namewhere} 🙋‍♂️ Домашний
          интернет в квартиру | Тарифы и акции на интернет - On-wifi
        </title>
        <meta
          name="description"
          content={
            "Какой интернет подключить " +
            cityData.infoDistrict.name +
            "➡️ Выбрать интернет на квартиру в " +
            cityData.infoDistrict.namewhere +
            " 🌐 Выбрать лучший тариф на домашний интернет"
          }
        />
        <meta name="apple-mobile-web-app-title" content="On-wifi" />
      </Head>
      <Header></Header>
      <Main></Main>
      <ProvidersInCity
        providers={cityData.providers}
        nameLocationWhere={cityData.infoDistrict.namewhere}
      ></ProvidersInCity>
      <SliderTariffsMain
        nameCityWhere={cityData.infoDistrict.namewhere}
        tariffs={cityData.tariffs}
      ></SliderTariffsMain>
      <AboutUs></AboutUs>
      <Advantages></Advantages>
      <ConnectionSteps></ConnectionSteps>
      <HelpForm></HelpForm>
      <Questions></Questions>
      <Cities></Cities>
      <Newsletter></Newsletter>
      <Footer></Footer>
      <PopUpLead></PopUpLead>
      <PopUpAgreement></PopUpAgreement>
      <PopUpPolicy></PopUpPolicy>
    </>
  );
};

export async function getStaticPaths() {
  const cities = [
    "Tyumen",
    "Borovsky",
    "Saint Petersburg",
    "Vsevolozhsk",
    "Bugulma",
    "Belorechensk",
    "Dno",
    "Leninogorsk",
    "Aksay",
    "Schekino",
    "Mendeleevsk",
    "Rezh",
    "Pechory",
    "Pytalovo",
    "Markova",
    "Kstovo",
    "Dudinka",
    "Kokhma",
    "Aznakaevo",
    "Nevel",
    "Narimanov",
    "Opochka",
    "Furmanov",
    "Borisoglebsk",
    "Mikhaylovsk",
    "Anosino",
    "Suzdal",
    "Gryazi",
    "Anapa",
    "Vityazevo",
    "Novosokolniki",
    "Zelenodolsk",
    "Belaya Kalitva",
    "Zainsk",
    "Yelabuga",
    "Ishimbay",
    "Porkhov",
    "Stroitel",
    "Akhtubinsk",
    "Rybnoye",
    "Shuya",
    "Mineralnye Vody",
    "Ostrov",
    "Petushki",
    "Nizhnekamsk",
    "Dmitrievka",
    "Beloretsk",
    "Almetyevsk",
    "Ursala",
    "Maykop",
    "Sterlitamak",
    "Neftekamsk",
    "Salavat",
    "Ufa",
    "Nagayevo",
    "Ulan-Ude",
    "Elista",
    "Volzhsk",
    "Yakutsk",
    "Kazan",
    "Naberezhnye Chelny",
    "Kyzyl",
    "Sputnik",
    "Glazov",
    "Izhevsk",
    "Zapadnye Shundy",
    "Sarapul",
    "Votkinsk",
    "Mozhga",
    "Barnaul",
    "Prigorodny",
    "Belmesevo",
    "Yuzhny",
    "Biysk",
    "Novorossiysk",
    "Tsemdolina",
    "Gelendzhik",
    "Volkovka",
    "Adler",
    "Khosta",
    "Krasnaya Polyana",
    "Plastunka",
    "Orel-Izumrud",
    "Kraevsko-Armyanskoe",
    "Vysokoe",
    "Baranovka",
    "Baranovka",
    "Estosadok",
    "Kazachiy Brod",
    "Veseloye",
    "Verkhniy Yurt",
    "Razdolnoye",
    "Krasnodar",
    "Starokorsunskaya",
    "im. Demyana Bednogo zhiloiy massi",
    "TEC zhiloiy massi",
    "Pashkovsky zhiloiy massi",
    "Norilsk",
    "Lesozavodsk",
    "Ussuriysk",
    "Timiryazevsky",
    "Vladivostok",
    "Nakhodka",
    "Yessentuki",
    "Pyatigorsk",
    "Kislovodsk",
    "Nevinnomyssk",
    "Stavropol",
    "Zheleznovodsk",
    "Amursk",
    "Komsomolsk-on-Amur",
    "Khabarovsk",
    "Belogorsk",
    "Svobodny",
    "Blagoveshchensk",
    "Mirny",
    "Mirny",
    "Severodvinsk",
    "Lesnaya Polyana",
    "Koryazhma",
    "Astrakhan",
    "Znamensk",
    "Stary Oskol",
    "Belgorod",
    "Vladimir",
    "Yuryevets",
    "Volgograd",
    "Vologda",
    "Molochnoe",
    "Cherepovets",
    "Voronezh",
    "Ivanovo",
    "Zvezdny",
    "Irkutsk",
    "Kaluga",
    "Petropavlovsk-Kamchatsky",
    "Zavodskoy",
    "Central",
    "Novoilyinsky",
    "Kuibyshevsky",
    "Aprelevka",
    "Mezhdurechensk",
    "Osinniki",
    "Kirov",
    "Gubkin",
    "Ganino",
    "Sadakovsky",
    "Doronichi",
    "Lyangasovo",
    "Raduzhny",
    "Kirovo-Chepetsk",
    "Kurgan",
    "Shchigry",
    "Kurchatov",
    "Kursk",
    "Zheleznogorsk",
    "Sosnovy Bor",
    "Yelets",
    "Lipetsk",
    "Magadan",
    "Sokol",
    "Uptar",
    "Bor",
    "Sarov",
    "Nizhny Novgorod",
    "Arzamas",
    "Sosnovy",
    "Ivanovka",
    "Dzerzhinsk",
    "Veliky Novgorod",
    "Berdsk",
    "Novosibirsk",
    "Iskitim",
    "Ob",
    "Omsk",
    "Shuvalovo",
    "Ust-Slavyanka",
    "Kudrovo",
    "Murino",
    "Sergiyevo",
    "Borisovka",
    "Sochi",
    "Berezovyy",
    "Kemerovo",
    "Mariinsky",
    "Energetik",
    "Dagomys",
    "Sirius",
    "Mokhovaya Pad",
    "Yasny",
    "Buguruslan",
    "Novotroitsk",
    "Gai",
    "Buzuluk",
    "Orenburg",
    "Orsk",
    "Sorochinsk",
    "Orel",
    "Penza",
    "Zarechny",
    "Kuznetsk",
    "Krasnokamsk",
    "Dobryanka",
    "Polazna",
    "Vetlyany",
    "Merkushevo",
    "Nizhny Lukh",
    "Bor-Lenva",
    "Divya",
    "Chelva",
    "Tambov",
    "Golubyata",
    "Kamsky",
    "Kyzh",
    "Vilva",
    "Gorodishche",
    "Adishchevo",
    "Peremskoye",
    "Tyus",
    "Bobki",
    "Shkaryata",
    "Zalesnaya",
    "Ust-Garevaya",
    "Sen'kino",
    "Perm",
    "Novye Lyady",
    "Solikamsk",
    "Pskov",
    "Taganrog",
    "Donetsk",
    "Moscow",
    "Novoshakhtinsk",
    "Kamensk-Shakhtinsky",
    "Zavodskoy",
    "Shakhty",
    "Rostov-on-Don",
    "Gamma-Trud",
    "Truzhenik",
    "Rassvet",
    "Vinogradar",
    "Za druzhbu",
    "Aktsaets",
    "ST Rigel",
    "Chkalovets",
    "Mir",
    "Rostov-Glavny",
    "Rostselmashevets-Tovarishch",
    "Avangard-3",
    "Kosmos",
    "Personal'nykh pensionerov-2",
    "Botanik",
    "Impulse",
    "Sirius",
    "Sadovod-Lyubitel'",
    "Rosinka",
    "Lesovod",
    "RSM-Rassvet",
    "Pobeda",
    "Krasny Aksay",
    "Energiya",
    "Voskhod UVD",
    "Afganets",
    "Rostovskoe",
    "Garant",
    "Voskhod",
    "Sputnik",
    "Rostselmashevets",
    "SKVO",
    "Vostok",
    "Agroprom",
    "Izumrud",
    "Kolos",
    "Veteran-RSM",
    "Aero",
    "Svetly put'",
    "Impulse",
    "Michurinetz",
    "Kupava",
    "Zheleznodorozhnik",
    "Zhemchuzhina",
    "Krasny sadovod",
    "Proletarsky Molot",
    "Berezka",
    "Severny",
    "12th",
    "Melioratorov",
    "110th",
    "113th",
    "142th",
    "203",
    "Khleborob",
    "Pervy mikrorayon GPZ-23",
    "Zeleny Gorod",
    "Ilinka",
    "3rd",
    "1a",
    "5th",
    "6th",
    "6a",
    "2nd",
    "7th",
    "11th",
    "2nd",
    "Maloe Tumanovo",
    "Pokrovka",
    "Topolek",
    "Parus",
    "Impulse",
    "Dorozhnik",
    "Stroymashevets",
    "Sadovod",
    "Geolog",
    "Letnyaya berezka",
    "Kolobovshchina",
    "4th",
    "Voskhod-2",
    "Sadovod",
    "Vodokanalproekt",
    "Elektrik",
    "Oktyabr",
    "Lokomotiv",
    "Sovetsky Sadovod",
    "DGTF",
    "Severnaya Riviera",
    "Belaya Romashka",
    "Svetoch",
    "Luch",
    "Novocherkassk",
    "Gukovo",
    "Azov",
    "Bataisk",
    "Gidromekhanizator",
    "Ryazan",
    "Olympic Village",
    "Saratov",
    "Pervomaysky",
    "Novosokolovogorsky",
    "Balakovo",
    "Engels",
    "1st Microdistrict",
    "Berezovsky",
    "Pervouralsk",
    "Nizhnee Selo",
    "Kamyslov",
    "Degtyarsk",
    "Kamensk-Uralsky",
    "Nizhny Tagil",
    "Yekaterinburg",
    "Svetly",
    "Sovkhozny",
    "Smolensk",
    "Kotovsk",
    "Rasskazovo",
    "Tver",
    "Rzhev",
    "Tomsk",
    "Tula",
    "Kosaya Gora",
    "Mendeleevsky",
    "Gorelki",
    "4",
    "Tobolsk",
    "6",
    "15",
    "9",
    "3a",
    "3b",
    "7a",
    "8",
    "Centralny",
    "7",
    "3",
    "10",
    "Ishim",
    "Ulyanovsk",
    "Magnitogorsk",
    "Miass",
    "Chelyabinsk",
    "Gorny",
    "Chita",
    "Yaroslavl",
    "Pavlovsk",
    "Sestroretsk",
    "Pushkin",
    "Kolpino",
    "Krasnoe Selo",
    "Beloyarsky",
    "Nyagan",
    "Nizhnevartovsk",
    "16th",
    "10",
    "2",
    "9A",
    "12",
    "8th",
    "11B",
    "5th",
    "16A",
    "11",
    "3rd",
    "1st",
    "13th",
    "6th",
    "8A",
    "15th",
    "15th",
    "14th",
    "17th",
    "9th",
    "Surgut",
    "Pyt-Yakh",
    "5 Solnechny",
    "6 Pionerny",
    "1 Tsentralny",
    "3 Kedrovy",
    "10",
    "2",
    "9",
    "7",
    "3",
    "5",
    "4",
    "6",
    "1",
    "Severo-zapadnaya Kommunalnaya Zona",
    "Muravlenko",
    "Noyabrsk",
    "Vynapurovsky",
    "R",
    "Novy Urengoy",
    "Slavyansky",
    "Priozerny (poselok Sadovy)",
    "Zhivem (poselok Solontsy)",
    "Vishnevaya gorka (poselok Zapadny)",
    "SNTSN Kristall (ter Prigorodny selsovet)",
    "Sloboda (derevnya Krutye Vyselki)",
    "Svetly (derevnya Krutye Vyselki)",
    "Solnechny (derevnya Krutye Vyselki)",
    "Mostootryad",
    "Cherepichny",
    "Berezovy (rp Markova)",
    "Khiminstituta",
    "SNT Sudostroitel",
    "NST Energiya-3",
    "Udachnoe",
    "Ogonyok",
    "Myndaba",
    "Beydinga",
    "Mayagas",
    "Arylakh",
    "Arylakh",
    "Borogontsy",
    "Charang",
    "Syrdakh",
    "Novoe Devyatkino",
    "Khotitsy",
    "Solovi",
    "Cherekha",
    "Borisovichi",
    "Rodina",
    "Totskoe Vtoroe",
    "Sizevo",
    "Pervomaisky",
    "Pervomaisky",
    "Volodarsky",
    "Abaga",
    "Mikhaylovka",
    "Myandigi",
    "Bolugur",
    "Amga",
    "Balyktakh",
    "Byas-Kyuel",
    "Sambek",
    "Signal",
    "Signal",
    "NST Otdykh",
    "NT Otdykh",
    "Entuziast",
    "Churapcha",
    "Ytyk-Kyuel",
    "Patrusheva",
    "Dudareva",
    "Saltykovka",
    "Balashikha",
    "1 Maya",
    "Pavlino",
    "Ol'gino",
    "Savvino",
    "Gagarina",
    "Keramik",
    "Chernoe",
    "Pavlino",
    "Zheleznodorozhnyy",
    "Kuchino",
    "Rusavkino-Romanovo",
    "Nikol'sko-Arkhangel'skiy",
    "Purshevo",
    "Novoe Pavlino",
    "Bronnitsy",
    "Vidnoe",
    "Mamonovo",
    "Gorki Leninskie",
    "Kupilinka (derevnya Sapronovo)",
    "Golitsyno",
    "Gorki-10",
    "Dzerzhinskiy",
    "Dmitrov",
    "Dmitrovskoe",
    "Pavel'tsevo",
    "Dolgoprudnyy",
    "Khlebnikovo",
    "Zapadnyy",
    "Zhukovskiy",
    "Zvenigorod",
    "Vostochnyy",
    "Ivanteevka",
    "Il'inskiy",
    "Il'inskoe",
    "Kotelniki",
    "Krasnoarmeysk",
    "Opalikha",
    "Nakhabino",
    "Krasnogorsk",
    "Otradnoe",
    "Petrovo-Dal'nee",
    "Lobnya",
    "Lytkarino",
    "Lyubertsy",
    "Malakhovka",
    "Mechnikovo",
    "Krivosheino",
    "Yamontovo",
    "Vnukovo",
    "Kommunarka",
    "Kokoshkino",
    "Krasnaya Pakhra",
    "Semenkovo",
    "Kryokshino",
    "LMS",
    "Erino",
    "Rudnevo",
    "Zverevo",
    "Fominskoe",
    "Sosenki",
    "Rublyovo",
    "Klokovo",
    "dsk Michurinets",
    "Baklanovo",
    "Stradan'",
    "Sof'ino",
    "Rassudovo",
    "Zhukovka",
    "Voronovo",
    "Yakovlevskoe",
    "Puchkovo",
    "Gorodishche",
    "Molodtsy",
    "Romantsevo",
    "Vnukovo",
    "Kievskiy",
    "Krasnaya Pakhra",
    "Kuznetsovo",
    "Bylovo",
    "Ababurovo",
    "Vnukovo",
    "Kamenka",
    "Zelenograd",
    "Salkovo",
    "Ostafevo",
    "Popovka",
    "Tolstopaltsevo",
    "Pervomayskoe",
    "Mar'ino",
    "Postnikovo",
    "Desna",
    "Bryokhovo",
    "Mytishchi",
    "Ptitsefabriki",
    "Poselok Pirogovskiy",
    "Pirogovo",
    "Stepankovo",
    "Mebel'noy fabriki",
    "Naro-Fominsk",
    "Novoglagolevo",
    "Noginsk",
    "Belaya",
    "Yamkino",
    "Odintsovo",
    "Uspenskoe",
    "Staryy Gorodok",
    "Khlyupino",
    "Skokovo",
    "Yudino",
    "Dubki",
    "Akulovo",
    "Chapaevka",
    "Orekhovo-Zuevo",
    "Bud'kovo",
    "Podol'sk",
    "Klimovsk",
    "L'vovskiy",
    "Kuznechiki",
    "Aleksandrovka",
    "Dubrovitsy",
    "Ordyntsy",
    "Kut'ino",
    "Pozdnyakovo",
    "Putilkovo",
    "Celyuskinskiy",
    "Pushkino",
    "Tarasovka",
    "Eldigino",
    "Ashukino",
    "Zelenogradskiy",
    "Sofrino",
    "Cherkizovo",
    "Zavety Il'icha",
    "Ramenskoe",
    "Bykovo",
    "Zabolot'e",
    "Zakharikha",
    "Boyarkino",
    "Tatarintsevo",
    "Strokino",
    "Kratovo",
    "Ostrovtsy",
    "Dergaevo",
    "Pervomayka",
    "Verkhnee Myachkovo",
    "Druzhba",
    "Udel'naya",
    "Mirnyy",
    "Antonovo",
    "Kuznetsovo",
    'sovkhoza "Ramenskoe"',
    "Igumnovo",
    "Fedino",
    "Bykovo",
    "Yurovo",
    "Malyshevo",
    "DNP Usad'ba Voronova",
    "Klishevo",
    "Zagornovo",
    "Reutov",
    "Sergiev Posad",
    "Serpukhov",
    "Verkhnee Shakhlovo",
    "sadovodcheskogo tovarishchestva Truzhenik",
    "Buturlino",
    "Kalugino",
    "Palikhovo",
    "Turovo",
    "Lipitsy",
    "Solnechnogorsk",
    "Povarovo",
    "Stupino",
    "Malino",
    "Mikhnevo",
    "Gridyukino",
    "Khimki",
    "Levoberezhnyy",
    "Podrezkovo",
    "Starbeevo",
    "Mezhdunarodnyy",
    "Bryokhovo",
    "Skhodnya",
    "DNTsN Blagoveshchenka (derevnya Blagoveshchenka)",
    "Blagoveshchenka",
    "DNP Zelenaya usad'ba (derevnya Ligachyovo)",
    "Firsanovka",
    "Yurlovo",
    "Chyornaya",
    "Chesnokovo",
    "Vaskino",
    "Ivino",
    "Chekhov",
    "Bershovo pole (derevnya Bershovo)",
    "Pokrov",
    "Lyubuchany",
    "Yuzhnye ozera-2 (derevnya Masnovo-Zhukovo)",
    "Lyutoretskoye",
    "Khlevino",
    "Alferovo",
    "Novgorodovo",
    "Kostomarovo",
    "Romashkino-2 (derevnya Gorelovo)",
    "Molodi",
    "Sharapovo",
    "Stremilovo",
    "Lisichkino (derevnya Popovo)",
    "Dubki plyus (poselok Vaskino)",
    "Elektrostal'",
    "Pishchevik",
    "Il'inskoe-Usovo",
    "3-y Kapotnya",
    "1-y Kapotnya",
    "Nemchinovo",
    "Bol'shie Vyzemy",
    "Berezki",
    "Novoe",
    "Shchelkovo",
    "Maysky",
    "Shebekino",
    "Kaliningrad",
    "Yantarny",
    "Kalinovoe Ozero",
    "Voroshnevo",
    "Gatchina",
    "Sosnovo",
    "Vyborg",
    "Boksitogorsk",
    "Luga",
    "Kirishi",
    "Primorsk",
    "Priozersk",
    "Yanino-1",
    "Nikolskoye",
    "Tikhvin",
    "Syasstroy",
    "Poroshkino",
    "Korobitsyno",
    "Michurinskoye",
    "Moscow",
    "Moscow",
    "Klin",
    "Dubna",
    "Fedurnovo",
    "Kupavna",
    "Yantarny",
    "Zhukovsky",
    "Yakhroma",
    "Vysokovsk",
    "Novoe Grishino",
    "Zarya",
    "Timonovo",
    "Lozhki",
    "Severomorsk",
    "Murmansk",
    "Mtsensk",
    "Kromy",
    "Znamenka",
    "Zhilina",
    "Zarechensky",
    "Obraztsovo",
    "Naryshkino",
    "Volgodonsk",
    "Samara",
    "Yugorsk",
    "Khanty-Mansiysk",
    "Kogalym",
    "Langepas",
    "Pokachi",
    "Roslyakovo",
    "Fokino",
    "Kronstadt",
    "Pargolovo",
    "Petro-Slavyanka",
    "Peterhof",
    "Strelna",
    "Pesochny",
    "Novocheboksarsk",
    "Cheboksary",
    "Kanash",
    "Shumerlya",
    "Alekseevka",
    "Valuyki",
    "Gostishchevo",
    "Rovenki",
    "Urazovo",
    "Proletarsky",
    "Krapivnoe",
    "Prokhorovka",
    "Kolotilovka",
    "Alekseevka",
    "Zadonsk",
    "Rastoropovo",
    "Belousovo",
    "Marushkino",
    "Volokhovo",
    "Molochny",
    "Nikel",
    "Shonguy",
    "Liinakhamari",
    "Tumanny",
    "Tara",
    "Troitskoye",
    "Mertsalovo",
    "Konevka",
    "Slavyanka",
    "Vladimiro-Aleksandrovskoye",
    "Zarubino",
    "Ekaterinovka",
    "Portyannikovo",
    "Piskovichi",
    "Bezhanitsy",
    "Dedovichi",
    "Gdov",
    "Pushkinskiye Gory",
    "Tyamsha",
    "Pustoshka",
    "Palkino",
    "Sosny",
    "Salsk",
    "Lenina",
    "Nekrasovo",
    "Topolevo",
    "Talinka",
    "Bely Yar",
    "Sovetsky",
    "Barsovo",
    "Solnechny",
    "Sergino",
    "Shumerlya",
    "Zmiyevka",
  ];

  const paths = cities.map((city) => ({
    params: { city },
  }));

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }: any) {
  const res = await fetch(`${api}/fullInfoDistrictByEndName/${params.city}`);
  const cityData = await res.json();

  return {
    props: {
      cityData,
    },
  };
}

export default CityPage;
